version: '3.9'
services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v4
    volumes:
      - ./config/file/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535